// Generated by CoffeeScript 1.6.3
var calculator, make_numbers_string, _;

_ = require('underscore');

make_numbers_string = function() {
  var i, possible, text, _i;
  text = "";
  possible = "0123456789";
  for (i = _i = 0; _i < 1000; i = _i += 1) {
    text += possible.charAt(Math.floor(Math.random() * possible.length));
  }
  return text;
};

calculator = function(input) {
  var largest_product;
  largest_product = 0;
  _.each(input, function(n, index) {
    var sum;
    sum = _.reduce(_.take(_.rest(input, index), 5), function(memo, num) {
      return memo * num;
    }, 1);
    return largest_product = sum > largest_product ? sum : largest_product;
  });
  return largest_product;
};

console.log(calculator(make_numbers_string()));
