// Generated by CoffeeScript 1.6.3
var calculator, make_numbers_string, _;

_ = require('underscore');

make_numbers_string = function() {
  var i, possible, text, _i;
  text = "";
  possible = "0123456789";
  for (i = _i = 0; _i < 1000; i = _i += 1) {
    text += possible.charAt(Math.floor(Math.random() * possible.length));
  }
  return text;
};

calculator = function(input) {
  return _.max(_.map(input, function(a, index, c) {
    return _.reduce(_.take(_.rest(input, index), 5), function(memo, num) {
      return memo * num;
    }, 1);
  }));
};

console.log(calculator(make_numbers_string()));
